### PR TITLE
Rego1000 3.14 variables

### PR DESCRIPTION
**Pull request by gunstr**
@jagheterfredrik an amazing piece of code you have put together - many thanks for that!

I just got a new IVT Greenline HE installed and have for now connected an ESP32-EVB board running the Rego 1000 component.

The firmware release in the rego1000 is 3.14 why I had to create a new configuration, the result is shared in this PR.

The parameters for ENERGY_OUTPUT has changed between 3.9 and 3.14. What I can see there is no data for the overall energy that has a good match with the sensor you have defined. Not really sure what is the best way to handle, but for now I have just commented out that sensor.

### CODE REVIEW

**Comment by jagheterfredrik** [comment]
Awesome! Would you mind adding a smoke test for it here: https://github.com/jagheterfredrik/esphome-rego1000/blob/main/.github/workflows/esphome.yml (in this PR)? 🙏

**Comment by gunstr** [comment]
Sure - done!

**Comment by gunstr** [comment]
How do you suggest to handle the Energy output sensor? Personally I will probably not use it but is there a way to have conditional sensors depending on the version? Such sensors can of course be moved to the variable yaml but that would mess up your architecture...

**Comment by jagheterfredrik** [comment]
Thank you for your contribution 🙏 Let's 🙈 regarding the sensor, the `rego1000.yaml` is really just an example and one has to customize it to ones needs anyway.

**Pull request merged**
